### PR TITLE
add Display,  ButtonPanel, and Button components : Milestone 2

### PR DESCRIPTION
**Pull request by moinkhanif**
This pull request features the following:
- Created these components:
   - Display
   - ButtonPanel
   - Button
- Passed in required props to Display and Button components
- Configured ButtonPanel to render respective buttons
- Styled the components

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @moinkhanif, great job on this project :100: The App is set up as required :+1: All components created as required :smile: The only issues I can point out are as follows:
- The README file must reflect the given milestone. Currently, the README file looks like the default README for react applications. Let us change it
- Let us add a "click handler" to the Buttons in the ButtonPanel Component. Let the example below, NB: "this" is from a class component", kindly omit the "this" keyword in the function components
hdg

Once these are fixed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by moinkhanif** [comment]
Hey @addod19 , the milestone doesn't talk about readme, but I'll update it as requested. I also wanted to clarify that I do not have any event handlers yet since this is Milestone 2. I believe you reviewed a different code.

**Comment by addod19** [comment]
> Hey @addod19 , the milestone doesn't talk about readme, but I'll update it as requested. I also wanted to clarify that I do not have any event handlers yet since this is Milestone 2. I believe you reviewed a different code.

Yes, I know but README serves as a guide for our project. It is professional to have a good README file. For the event handlers, we can create it but not necessarily functional as in the screenshot

**Review by trekab — APPROVED** [review]
### Approved! :tada: 
Congratulations, @moinkhanif! You have met this milestone's requirements. I commend you for working on the __optional__ requirements suggested in the last review and we apologise for passing them to you as mandatory.

_Happy coding!_ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Pull request merged**
